blank_issues_enabled: false

contact_links:
  - name: Community Discussions
    url: https://github.com/Hrdtr/devu/discussions
    about: Please ask and answer questions here.

  - name: 📚 Devu Documentation
    url: https://github.com/Hrdtr/devu#readme
    about: Check the documentation for usage of Devu
